# Generated by Django 4.2.9 on 2024-04-23 04:23

import contactus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetail',
            name='mobile_number',
            field=models.CharField(max_length=10, validators=[contactus.models.validate_mobile_number]),
        ),
    ]
